# .streamlit/secrets.toml
MONGO_URI = "mongodb+srv://randalltoerien_db_user:4cDJN0WFRkIKpFc7@cluster0.mongodb.net/?retryWrites=true&w=majority"
MONGO_DB = "app_db"

# add Slack/email credentials
SLACK_WEBHOOK = "https://hooks.slack.com/services/..."
EMAIL_USER = "your@email.com"
EMAIL_PASS = "your_app_password"
